// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloword

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreaterClient is the client API for Greater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreaterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greaterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreaterClient(cc grpc.ClientConnInterface) GreaterClient {
	return &greaterClient{cc}
}

func (c *greaterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloword.Greater/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreaterServer is the server API for Greater service.
// All implementations must embed UnimplementedGreaterServer
// for forward compatibility
type GreaterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreaterServer()
}

// UnimplementedGreaterServer must be embedded to have forward compatible implementations.
type UnimplementedGreaterServer struct {
}

func (UnimplementedGreaterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreaterServer) mustEmbedUnimplementedGreaterServer() {}

// UnsafeGreaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreaterServer will
// result in compilation errors.
type UnsafeGreaterServer interface {
	mustEmbedUnimplementedGreaterServer()
}

func RegisterGreaterServer(s grpc.ServiceRegistrar, srv GreaterServer) {
	s.RegisterService(&Greater_ServiceDesc, srv)
}

func _Greater_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreaterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloword.Greater/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreaterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greater_ServiceDesc is the grpc.ServiceDesc for Greater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloword.Greater",
	HandlerType: (*GreaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greater_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/greater.proto",
}
