---
services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    ports:
     - 9200:9200
     - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - elk

  logstash:
    image: logstash:${ELK_VERSION}
    ports:
      - 5000:5000
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: kibana:${ELK_VERSION}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
