version: '3.3'

prometheus:
  image: prom/prometheus
  links:
    - graphite-statsd
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - 9090:9090

graphite-statsd:
  image: graphiteapp/graphite-statsd
  restart: always
  ports:
    - 80:80
    - 2003-2004:2003-2004
    - 2023-2024:2023-2024
    - 8125:8125/udp
    - 8126:8126

grafana:
  image: grafana/grafana
  ports:
    - 3000:3000
