scrape_configs:
  - job_name: 'app'
    scrape_interval: 1s
    static_configs:
      - targets:
        - app:8081
  - job_name: 'node'
    scrape_interval: 1s
    static_configs:
      - targets:
        - node_exporter:9100
