scrape_configs:
  - job_name: 'app'
    scrape_interval: 1s
    static_configs:
      - targets:
        - app:8081
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
